---
version: 2.1

executors:
  gpu:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
      docker_layer_caching: true
    resource_class: gpu.nvidia.medium   
  linux:
    machine:
      image:
      docker_layer_caching: true
    resource_class: medium

jobs:
  build_image:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    working_directory: /home/circleci/project
    environment:
      DOCKER_BUILDKIT: '1'
      BUILDKIT_PROGRESS: plain
    steps:
      - checkout
      - run:
          name: Build images
          command: |
            docker-compose --ansi=never -f docker-compose.yml build

workflows:
  pipeline:
    jobs:
      - build_image:
          matrix:
            parameters:
              exec:
                - gpu
                - linux
